/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaBoolector */

#ifndef _Included_JavaBoolector
#define _Included_JavaBoolector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaBoolector
 * Method:    jbtor
 * Signature: ()V
 */


JNIEXPORT void JNICALL Java_JBtor_jbtorC
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_JBtor_jbtorReleaseC
        (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_JBoolectorNode_jboolectorVarC
        (JNIEnv *, jobject, jlong, jstring);

JNIEXPORT jlong JNICALL Java_JBoolectorNode_jboolectorCopyC
        (JNIEnv *, jobject, jlong);

JNIEXPORT jlong JNICALL Java_JBoolectorNode_jboolectorXorC
        (JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_JBoolectorNode_jboolectorEqC
        (JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_JBoolectorNode_jboolectorAndC
        (JNIEnv *, jobject, jlong, jlong);

JNIEXPORT jlong  JNICALL Java_JBoolectorNode_jboolectorNotC
        (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_JBoolectorNode_jboolectorAssertC
        (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_JBoolectorNode_jboolectorReleaseC
        (JNIEnv *, jobject, jlong);


JNIEXPORT jlong JNICALL Java_JBoolectorSort_jboolectorBitvecSortC
        (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_JBoolectorNode_jboolectorReleaseSortC
        (JNIEnv *, jobject, jlong);

JNIEXPORT jint JNICALL Java_JBoolectorSat_jboolectorSatC
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
